version: "2"
services:
  mongodb:
    image: mongo
    container_name: mongodb
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: mongo
#      MONGO_INITDB_ROOT_PASSWORD: mongo
    volumes:
      - $HOME/mongodb/database:/data/db
    ports:
      - 27017:27017
    restart: "no"
  mongo-express:
    image: mongo-express
    restart: "no"
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
#      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
#      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
      ME_CONFIG_MONGODB_URL: mongodb://mongo:mongo@mongodb:27017/
    depends_on:
      - mongodb